## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

name: Sample App Deployment - Python S3
on:
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

env:
  E2E_TEST_ACCOUNT_ID: ${{ secrets.APPLICATION_SIGNALS_E2E_TEST_ACCOUNT_ID }}
  E2E_TEST_ROLE_NAME: ${{ secrets.APPLICATION_SIGNALS_E2E_TEST_ROLE_NAME }}

jobs:
  python-zip:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-east-1' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.E2E_TEST_ACCOUNT_ID }}:role/${{ env.E2E_TEST_ROLE_NAME }}
          aws-region: us-east-1

      - name: Retrieve account
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids:
            ACCOUNT_ID, region-account/${{ matrix.aws-region }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.E2E_TEST_ROLE_NAME }}
          aws-region: ${{ matrix.aws-region }}

      - name: Build Sample App Zip
        working-directory: sample-apps/python
        run: zip -r python-sample-app.zip .

      - name: Upload to S3
        working-directory: sample-apps/python
        run: aws s3api put-object --bucket aws-appsignals-sample-app-prod-${{ matrix.aws-region }}-2 --body ./python-sample-app.zip --key python-sample-app.zip

      - name: Build Lambda Sample App
        uses: actions/checkout@v4
        with:
          repository: 'aws-observability/aws-otel-python-instrumentation'
      - name: Build sample lambda function
        shell: bash
        run: ./package-lambda-function.sh
        working-directory: lambda-layer/sample-apps

      - name: Upload to Lambda Sample App to S3
        working-directory: lambda-layer/sample-apps
        run: aws s3api put-object --bucket aws-appsignals-sample-app-prod-${{ matrix.aws-region }}-2 --body ./build/function.zip --key pyfunction.zip


        